apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
      maxSurge: 3
  template: 
    metadata:
      labels:
        app: gateway
    spec:
      - name: gatway
        image: jamiechiu/gatway
        envFrom:
        - configMapRef:
            name: gateway-configmap
        - secretRef:
            name: gateway-secret

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports: 
    - port: 8080
      targetPort: 8080
      protocol: TCP
